DisplayName: "[&eOrderSign&f] "

signs:
    Disposal:
        cost: 15000
        permission: "ordersign.disposal"
        lines:
            1: "&1[Disposal]"
            2: ""
            3: ""
            4: ""
    Spawn:
        cost: 15000
        permission: "ordersign.spawn"
        lines:
            1: "&1[Warp]"
            2: "Spawn"
            3: ""
            4: ""