name: OrderSign
author: seemethere
main: com.github.seemethere.OrderSign.OrderSign
version: $version$

commands:
    ordersign:
        description: Basic command for the plugin
        usage: /<command> argument
        aliases: [sign]

